### ISSUE TITLE
[Bug] Pin tooltip is not working

### ISSUE THREAD

**Issue by leanton** [keplergl/kepler.gl#1509]
**Describe the bug**

**To Reproduce**
1. Run the latest version of kepler.gl demo locally
2. Open sample data (e.g. earthquakes)
3. Hover over the polygon
4. Click on the polygon
5. Expected: a tooltip is pinned
6. Actual: a tooltip is hidden

https://user-images.githubusercontent.com/4489795/122260283-fd1a3180-ceca-11eb-9f9e-878d0fabf3ce.mov

**Expected behavior**
When clicked on a layer the tooltip is pinned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs BigSur
 - Browser: Chrome
 - Version: 91

**Additional context**
In the deployed example, the bug is not produced: https://kepler.gl/demo/county_unemployment

Could it be because the dependency versions are not fixed?

**Comment by staufferl16** [comment]
^ Seconding this bug as well.

When I inspect the props of the MapContainer, I see that `coordinate` and `mousePosition` are defined in the `mousePos` prop.  This `mousePos` prop is supposed to get deconstructed  and passed down to the rendered child component made by the MapPopoverFactory. However, when the component is made by MapPopoverFactory, the `x`, `y`, and `coordinates` are not passed.

**Comment by leanton** [comment]
Hi @staufferl16, thanks for the reply

> ^ Seconding this bug as well.

Sorry, I did not get it. Is this a known bug and there is a PR that fixes it? Or there is a way to fix it within demo app codebase?

**Comment by staufferl16** [comment]
@leanton , I'm not sure if it's known by the keplergl team yet.  If the issue was occurring at the component factory level, it could be something that you could fix by overriding the factory component (as outlined in the README.md).  But, the issue is happening at the container level: the coordinate prop is getting clobbered.

I'm going to see if I can get a PR going for a proposed fix.  If I get that working, you could check out that branch & confirm the fix locally on your machine potentially.

**Comment by staufferl16** [comment]
@leanton , it turns out my problem was not related & is resolved in master (but not the latest release).  Sorry for the false alarm!  I'm not sure what's going on here exactly.  I was able to get this to work locally, too.
Maybe make sure you've got the updated dependencies.  I started mine from scratch & everything worked without a hitch.

Sorry I couldn't be more help!

**Comment by leanton** [comment]
@staufferl16 could you please share your `package-lock.json` or `yarn.lock` so I can fix the dependencies?

**Comment by staufferl16** [comment]
[yarn-lock-copy.txt](https://github.com/keplergl/kepler.gl/files/6716401/yarn-lock-copy.txt)

**Comment by staufferl16** [comment]
@leanton Sure thing!  Here's what I have. ^

**Comment by leanton** [comment]
@staufferl16 thanks, with your `yarn.lock` file the issue disappeared!

However, it's still reproducible if I remove lock file and node_modules and do `yarn && yarn.start` 
Thus, I will keep the issue open

**Comment by GuyShaanan** [comment]
Isn't it related to this? https://github.com/keplergl/kepler.gl/issues/1419

**Comment by staufferl16** [comment]
@GuyShaanan Thank you SO MUCH!!  That is totally what was causing my problems!  Pinning the deck.gl libraries in my `resolutions` section fixed everything! It was indeed related.
